import fontforge
import shutil
import os
from tomlkit.toml_file import TOMLFile, TOMLDocument
from typing import Iterable, Optional, Union

fontbakery_path = None
fontspector_path = None
fontbakery_config = TOMLDocument()
fontspector_config = TOMLDocument()

plugin_config = TOMLDocument()
_plugin_dir = ''
CONFIGFILE = 'config.toml'
FONTBAKERY_CONFIGFILE = 'fontbakery.toml'
FONTSPECTOR_CONFIGFILE = 'fontspector.toml'

FBFS_CONFIG_HEADER = (
    "# This file is automatically generated with fontforge-fontchecker plugin.\n"
    "# Do not edit.\n\n"
)

profiles = {
    'opentype': 'OpenType (standards compliance)',
    'universal': 'Universal (community best practice)',
    'googlefonts': 'Google Fonts',
    'iso15008': 'ISO 15008 (in-car accessibility)',
    'fontwerk': 'Fontwerk',
    'adobefonts': 'Adobe Fonts',
    'fontbureau': 'Font Bureau',
    'microsoft': 'Microsoft',
    'notofonts': 'Noto fonts',
    'typenetwork': 'Type Network',
}
"""List of known Fontbakery/Fontspector check profile"""


def checkFontTools():
    global fontbakery_path, fontspector_path
    fontbakery_path = shutil.which('fontbakery')
    fontspector_path = shutil.which('fontspector')


def _validateConfItem(key: str, defaultVal, *, choice: Optional[Iterable] = None) -> bool:
    loaded = True
    if (key not in plugin_config) or (not isinstance(plugin_config[key], type(defaultVal))):
        plugin_config[key] = defaultVal  # load default
        loaded = False
    if isinstance(defaultVal, dict) and isinstance(plugin_config[key], dict):
        if missingKeys := defaultVal.keys() - plugin_config[key].keys():
            plugin_config[key] |= dict((k, v) for k, v in defaultVal.items() if k in missingKeys)
    if choice:
        if not any(plugin_config[key] == x for x in choice):
            fontforge.logWarning("Invalid " + key + " '" + str(plugin_config[key]) + "' ignored")
            plugin_config[key] = defaultVal
    return loaded


def _setOrRemove(key: str, val):
    if val is not None:
        plugin_config[key] = val
    elif key in plugin_config:
        plugin_config.remove(key)


def _validateConfItemType(key: str, typeobj: type, defaultVal=None):
    if key in plugin_config:
        try:
            plugin_config[key] = typeobj(plugin_config[key])
        except Exception as e:
            if key in plugin_config:
                fontforge.logWarning('Configuration error in {}! Using default {}\n{}: {}'.format(
                    key, str(defaultVal), type(e).__name__, str(e)
                ))
            _setOrRemove(key, defaultVal)


def _addDoNotEditHeader(config: TOMLDocument) -> TOMLDocument:
    import tomlkit
    myToml = config.as_string()
    if not myToml.startswith(FBFS_CONFIG_HEADER):
        myToml = FBFS_CONFIG_HEADER + myToml
        return tomlkit.parse(myToml)
    return config


def _validateConf():
    global profiles
    _validateConfItem('backend', 'auto', choice=['auto', 'fontbakery', 'fontspector'])
    _validateConfItem('check_as', 'ttf', choice=['ttf', 'ufo'])
    _validateConfItem('glyph_result', {
        'color': False, 'comment': False,
        'FAIL': 0xff0000, 'WARN': 0xffff00,
    })
    if _validateConfItem('profiles', profiles):
        profiles |= plugin_config['profiles']
    if _validateConfItem('profile', 'universal'):
        if plugin_config['profile'] not in profiles:
            profiles[plugin_config['profile']] = plugin_config['profile']
    _validateConfItem('explicit_checks', [])
    _validateConfItem('exclude_checks', [])
    _validateConfItem('network_check', {
        'timeout': 0,
        'skip': False,
    })
    _validateConfItemType('warn_size', int)
    _validateConfItemType('fail_size', int)
    _validateConfItemType('fatal_size', int)
    _validateConfItem('explicit_files', {})
    _validateConfItem('exclude_files', {})


def fontBakeryConfigFile() -> str:
    return _plugin_dir + '/' + FONTBAKERY_CONFIGFILE


def fontSpectorConfigFile() -> str:
    return _plugin_dir + '/' + FONTSPECTOR_CONFIGFILE


def loadConf(confdir: str):
    global _plugin_dir, plugin_config, fontbakery_config, fontspector_config
    _plugin_dir = confdir
    try:
        plugin_config = TOMLFile(_plugin_dir + '/' + CONFIGFILE).read()
    except FileNotFoundError:
        pass

    _validateConf()

    try:
        fontbakery_config = TOMLFile(fontBakeryConfigFile()).read()
    except FileNotFoundError:
        pass
    try:
        fontspector_config = TOMLFile(fontSpectorConfigFile()).read()
    except FileNotFoundError:
        pass

    fontbakery_config = _addDoNotEditHeader(fontbakery_config)
    fontspector_config = _addDoNotEditHeader(fontspector_config)


def saveConf():
    os.makedirs(_plugin_dir, exist_ok=True)
    TOMLFile(_plugin_dir + '/' + CONFIGFILE).write(plugin_config)
    TOMLFile(_plugin_dir + '/' + FONTBAKERY_CONFIGFILE).write(fontbakery_config)
    TOMLFile(_plugin_dir + '/' + FONTSPECTOR_CONFIGFILE).write(fontspector_config)


def _writeBackendExplicitExcludeFileConf():
    tags = ['warn_size', 'fail_size', 'fatal_size']
    sizeconf = any(tag in plugin_config for tag in tags)
    sizeconf_b = any(tag in plugin_config for tag in ['warn_size', 'fail_size'])
    check_ids = sorted(set(
        c.strip() for c in
        list(plugin_config['explicit_files']) + list(plugin_config['exclude_files']) +
        (['file_size'] if sizeconf else [])
    ))
    for check_id in check_ids:
        fontspector_config.setdefault(check_id, {})
        for purpose in ['explicit_files', 'exclude_files']:
            if check_id in plugin_config[purpose]:
                fontspector_config[check_id][purpose] \
                    = plugin_config[purpose][check_id]
            else:
                if purpose in fontspector_config[check_id]:
                    fontspector_config[check_id].remove(purpose)
        if check_id == 'file_size':
            for tag in tags:
                if tag in plugin_config:
                    fontspector_config['file_size'][tag.upper()] = plugin_config[tag]
                    if sizeconf_b and tag != 'fatal_size':
                        fontbakery_config.setdefault('file_size', {})
                        fontbakery_config['file_size'][tag.upper()] = plugin_config[tag]


def _writeBackendConf():
    import tomlkit
    global fontbakery_config, fontspector_config
    fontbakery_config = tomlkit.parse(FBFS_CONFIG_HEADER)
    fontspector_config = tomlkit.parse(FBFS_CONFIG_HEADER)

    fontspector_config['explicit_checks'] \
        = fontbakery_config['explicit_checks'] \
        = plugin_config['explicit_checks']
    fontspector_config['exclude_checks'] \
        = fontbakery_config['exclude_checks'] \
        = plugin_config['exclude_checks']
    _writeBackendExplicitExcludeFileConf()
    for conf in (fontspector_config, fontbakery_config):
        for i in [x[0] for x in conf.items() if not x[1]]:
            conf.remove(i)


def _colorValToStr(col: Union[str, int]) -> str:
    if isinstance(col, int):
        return format(col, '06x')
    else:
        return str(col).removeprefix('#')


def _colorStrToVal(col: str) -> Union[str, int]:
    try:
        return int(str(col).removeprefix('#'), 16)
    except ValueError:
        return str(col)


def getColorVal(col: Union[str, int], defaultCol: int = -1) -> str:
    if isinstance(col, int):
        return col
    elif isinstance(colval := _colorStrToVal(col), int):
        return colval
    else:
        try:
            from webcolors import name_to_hex
            return int(name_to_hex(str(col)).removeprefix('#'), 16)
        except ModuleNotFoundError as e:
            fontforge.logWarning(str(e))
            return defaultCol  # default color if webcolors unavailable
        except ValueError as e:
            fontforge.logWarning(str(e))
            return defaultCol  # default color if no such color


def _timeoutStrToVal(prm: str) -> int:
    try:
        return max(int(str(prm)), 0)
    except ValueError:
        return 0


def _parseExplicitExcludeFiles(prm: Optional[str]) -> dict[str, list[str]]:
    if prm is None:
        return {}
    resultDict: dict[str, list[str]] = {}
    prmlist = [el.strip() for el in prm.split(':')]
    for k, v in zip(prmlist[::2], prmlist[1::2]):
        resultDict.setdefault(k, [])
        resultDict[k].append(v)
    return resultDict


def _dumpExplicitExcludeFiles(prm: dict[str, list[str]]) -> str:
    if prm is None:
        return ''
    else:
        return ':'.join(':'.join(k + ':' + p for p in v) for k, v in prm.items())


def _filesizeExpressionToInt(filesizeExpression: str) -> int:
    from fractions import Fraction

    if not filesizeExpression:
        return None
    fs = filesizeExpression.lower()
    if fs.endswith('b') or fs.endswith('o'):
        fs = fs[:-1]
    factor = 1
    for s, f in [(p + i, f ** (v + 1)) for v, p in enumerate('kmgtpezyrq') for i, f in [('', 1000), ('i', 1024)]]:
        if fs.endswith(s):
            factor *= f
            fs = fs.removesuffix(s)
            continue
    return int(Fraction(fs.strip()) * factor)


def _intToFilesizeExpression(filesize: int) -> str:
    if filesize is None:
        return ''
    else:
        return str(filesize)


def configInterface():
    ans = fontforge.askMulti(
        'Configuration',
        [
            {
                'type': 'choice',
                'question': 'Backend',
                'tag': 'backend',
                'checks': True,
                'answers': [
                    {'name': p.capitalize(), 'tag': p, 'default': plugin_config['backend'] == p}
                    for p in ['auto', 'fontbakery', 'fontspector']
                ],
            },
            {
                'type': 'choice',
                'question': 'Check as',
                'tag': 'check_as',
                'checks': True,
                'answers': [
                    {'name': p, 'tag': p.lower(), 'default': plugin_config['check_as'] == p.lower()}
                    for p in ['TTF', 'UFO']
                ],
            },
            {
                'type': 'choice',
                'question': 'Result for glyphs',
                'tag': 'glyph_result',
                'checks': True,
                'multiple': True,
                'answers': [
                    {'name': p, 'tag': p.lower(), 'default': plugin_config['glyph_result'][p.lower()]}
                    for p in ['Color', 'Comment']
                ],
            },
            {
                'type': 'string',
                'question': 'Color for FAIL',
                'tag': 'color_fail',
                'default': _colorValToStr(plugin_config['glyph_result']['FAIL']),
            },
            {
                'type': 'string',
                'question': 'Color for WARN',
                'tag': 'color_warn',
                'default': _colorValToStr(plugin_config['glyph_result']['WARN']),
            },
            {
                'type': 'choice',
                'question': 'Profile',
                'tag': 'profile',
                'answers': [
                    {'name': p[1], 'tag': p[0], 'default': plugin_config['profile'] == p[0]}
                    for p in profiles.items()
                ],
            },
            {
                'type': 'string',
                'question': 'Explicit checks\n(comma-separated)',
                'tag': 'explicit_checks',
                'default': ','.join(plugin_config['explicit_checks']),
            },
            {
                'type': 'string',
                'question': 'Excluded checks\n(comma-separated)',
                'tag': 'exclude_checks',
                'default': ','.join(plugin_config['exclude_checks']),
            },
            {
                'type': 'string',
                'question': 'Explicit files per check\n(chkid:file:chkid:file:...)\n(Fontspector only)',
                'tag': 'explicit_files',
                'default': _dumpExplicitExcludeFiles(plugin_config['explicit_files']),
            },
            {
                'type': 'string',
                'question': 'Excluded files per check\n(chkid:file:chkid:file:...)\n(Fontspector only)',
                'tag': 'exclude_files',
                'default': _dumpExplicitExcludeFiles(plugin_config['exclude_files']),
            },
            {
                'type': 'string',
                'question': 'Ideal maximum file size',
                'tag': 'warn_size',
                'default': _intToFilesizeExpression(plugin_config.get('warn_size')),
            },
            {
                'type': 'string',
                'question': 'Acceptable maximum file size',
                'tag': 'fail_size',
                'default': _intToFilesizeExpression(plugin_config.get('fail_size')),
            },
            {
                'type': 'string',
                'question': 'Maximum file size of\nminor issue\n(Fontspector only)',
                'tag': 'fatal_size',
                'default': _intToFilesizeExpression(plugin_config.get('fatal_size')),
            },
            {
                'type': 'string',
                'question': 'Network check timeout',
                'tag': 'network_timeout',
                'default': str(plugin_config['network_check']['timeout']),
            },
            {
                'type': 'choice',
                'question': '',
                'tag': 'network',
                'checks': True,
                'multiple': True,
                'answers': [
                    {'name': 'Skip network check', 'tag': 'skip', 'default': plugin_config['network_check']['skip']},
                ],
            },
        ]
    )
    if ans:
        plugin_config['backend'] = ans['backend']
        plugin_config['check_as'] = ans['check_as']
        plugin_config['profile'] = ans['profile']
        plugin_config['glyph_result']['color'] = bool(ans['glyph_result'] and ('color' in ans['glyph_result']))
        plugin_config['glyph_result']['comment'] = bool(ans['glyph_result'] and ('comment' in ans['glyph_result']))
        plugin_config['glyph_result']['FAIL'] = _colorStrToVal(ans['color_fail'] or '')
        plugin_config['glyph_result']['WARN'] = _colorStrToVal(ans['color_warn'] or '')
        plugin_config['explicit_checks'] = [a.strip() for a in (ans['explicit_checks'] or '').split(',') if a]
        plugin_config['exclude_checks'] = [a.strip() for a in (ans['exclude_checks'] or '').split(',') if a]
        plugin_config['network_check']['timeout'] = _timeoutStrToVal(ans['network_timeout'] or 0)
        plugin_config['network_check']['skip'] = bool(ans['network'] and ('skip' in ans['network']))
        _setOrRemove('warn_size', _filesizeExpressionToInt(ans['warn_size']))
        _setOrRemove('fail_size', _filesizeExpressionToInt(ans['fail_size']))
        _setOrRemove('fatal_size', _filesizeExpressionToInt(ans['fatal_size']))
        plugin_config['explicit_files'] = _parseExplicitExcludeFiles(ans['explicit_files'] or '')
        plugin_config['exclude_files'] = _parseExplicitExcludeFiles(ans['exclude_files'] or '')
        _writeBackendConf()
        saveConf()
